version: '3.8'

services:
  mcp-server-asana:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server-asana-dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - ASANA_ACCESS_TOKEN=${ASANA_ACCESS_TOKEN}
      - DEFAULT_WORKSPACE_ID=${DEFAULT_WORKSPACE_ID:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PORT=8080
    volumes:
      # Mount source code for development (optional - for live reload)
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 